<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DetailsView.aspx.cs" Inherits="網頁整合.Try.DetailsView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="PLID" DataSourceID="SqlDataSource1">
                <Fields>
                    <asp:BoundField DataField="PLID" HeaderText="PLID" ReadOnly="True" SortExpression="PLID" />
                    <asp:BoundField DataField="language" HeaderText="language" SortExpression="language" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:網頁整合DBConnectionString %>" DeleteCommand="DELETE FROM [ProgrammingLanguage] WHERE [PLID] = @PLID" InsertCommand="INSERT INTO [ProgrammingLanguage] ([PLID], [language]) VALUES (@PLID, @language)" SelectCommand="SELECT * FROM [ProgrammingLanguage]" UpdateCommand="UPDATE [ProgrammingLanguage] SET [language] = @language WHERE [PLID] = @PLID">
                <DeleteParameters>
                    <asp:Parameter Name="PLID" Type="Byte" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="PLID" Type="Byte" />
                    <asp:Parameter Name="language" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="language" Type="String" />
                    <asp:Parameter Name="PLID" Type="Byte" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
